spring:
  application:
    name: shop

  datasource:
    url: jdbc:mariadb://localhost:3306/berryweb_shop
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

jwt:
  secret: ${JWT_SECRET:bXktc3VwZXItc2VjcmV0LWp3dC1zaWduaW5nLWtleS1mb3ItbWljcm9zZXJ2aWNlcy1zaG91bGQtYmUtdmVyeS1sb25nLTI1Ni1iaXRz}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}

file:
  upload:
    path: ${FILE_UPLOAD_PATH:/app/uploads}
    max-size: 10485760 # 10MB
    max-count: 10
    allowed-extensions: jpg,jpeg,png,gif,bmp

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  circuitbreaker:
    enabled: true

logging:
  level:
    com.boardsystem.shopservice: DEBUG